name: Semgrep Scan Test

on:
 pull_request:
   branches:
     - main

jobs:
 semgrep:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Semgrep
      run: |
        python -m pip install semgrep

    - name: Run Semgrep scan
      run: semgrep scan --config=auto . || echo "semgrep_failed=true" >> $GITHUB_ENV
    
    - name: Mensagem de Sucesso
      if: env.semgrep_failed!='true'
      run: echo "Nenhum problema encontrado pelo semgrep"
    - name: Mensagem se o Semgrep Falhar
      if: env.semgrep_failed=='true'
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: "Semgrep encontrou problemas no código"
content-filepath: .semgrep_issue.md
           


    

   