name: Semgrep Scan Test

on:
 pull_request:
   branches:
     - main

jobs:
 semgrep:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version:'3.x'

    - name: Install Semgrep
      run: |
        python -m install --upgrade pip install semgrep

    - name: Run Semgrep scan
      run: semgrep scan --config=auto

   