name: trufflehog scan

on:
  pull_request:
      branches:
        - main

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
    -  name: Checkout do Código
       uses: actions/checkout@v3

    - name: Instancia TruffleHog
      run: docker pull trufflesecurity/trufflehog:latest