name: trufflehog scan

on:
  pull_request:
      branches:
        - main

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
    -  name: Checkout do Código
       uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Trufflehog
      run: python -m  pip install trufflehog

    - name: Run Trufflehog
      run: trufflehog https://github.com/IBMEvangelista/Semgrep